/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 opepen.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/opepen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.top_.geometry} material={nodes.top_.material} position={[0, 4, 0]} />
      <mesh geometry={nodes.ring_light.geometry} material={materials['Material.001']} position={[-2, 5, 1]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.08, 1]} />
      <mesh geometry={nodes.Corner.geometry} material={nodes.Corner.material} position={[-1, 5, -1]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.504, 1]} />
      <mesh geometry={nodes.bottom.geometry} material={nodes.bottom.material} position={[-1, 0.5, 0]} scale={[2, 1, 4]} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-1, 5, -1]} />
    </group>
  )
}

useGLTF.preload('/opepen.glb')
