/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 opepen1.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";

export function Model(props) {
  const { nodes, materials } = useGLTF("../models/opepen2.glb");

  const [ringColor, setRingColor] = useState();

  const ref = useRef();
  const ball = useRef();
  const ring = useRef();
  const dLight = useRef();

  useEffect(() => {
    if (ball)
      if (ball.current.position.z === 1) {
        setRingColor("#bdfff");
      } else {
        setRingColor("#777");
      }
  }, [ball.current, ringColor]);

  return (
    <group ref={ref} {...props} dispose={null} rotation={[0, Math.PI * 1.5, 0]}>
      <mesh
        geometry={nodes.top_.geometry}
        material={materials.Material}
        position={[0, 4, 0]}
        receiveShadow
      />
      <mesh
        ref={ring}
        geometry={nodes.ring_light.geometry}
        material={materials["Material.001"]}
        position={[-2, 5, 1]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 0.08, 1]}
        material-color={ringColor}
      />
      <mesh
        geometry={nodes.Corner.geometry}
        material={materials["Material.003"]}
        position={[-1, 5, -1]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 0.504, 1]}
      />
      <mesh
        geometry={nodes.bottom.geometry}
        material={materials["Material.002"]}
        position={[-1, 0.5, 0]}
        scale={[2, 1, 4]}
      />
      <mesh
        ref={ball}
        geometry={nodes.Sphere.geometry}
        material={materials["Material.004"]}
        position={[-1, 5, 1]}
        castShadow
      />

      <directionalLight ref={dLight} castShadow />
      <pointLight position={[-2, 5, 1]} intensity={3} color={"#BDFFFF"} />

      <EffectComposer>
        <SelectiveBloom lights={[dLight]} selection={[ring]} />
      </EffectComposer>
    </group>
  );
}

useGLTF.preload("../models/opepen2.glb");
